name: Release
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
jobs:
  Release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Bun
        run: |
          curl -fsSL https://bun.sh/install | bash
          echo "$HOME/.bun/bin" >> $GITHUB_PATH
      - run: |
            cd client
            bun install
            bun run lint
            bun run test
      - name: create .env file
        run: |
          cd client
          mkdir -p env
          cd env 
          touch .env
          echo "VITE_PUBLIC_API_BASE_URL=${{ secrets.VITE_PUBLIC_API_BASE_URL }}" >> .env
          echo "VITE_SUPABASE_URL=${{ secrets.VITE_SUPABASE_URL }}" >> .env
          echo "VITE_SUPABASE_API_KEY=${{ secrets.VITE_SUPABASE_API_KEY }}" >> .env
          echo "VITE_STRIPE_CUSTOMER_PORTAL_URL=${{ vars.VITE_STRIPE_CUSTOMER_PORTAL_URL }}" >> .env
      - name: Build project
        run: |
          bun install
          cd client
          bun run build
      - name: Get current version and update
        run: |
          LATEST_TAG=$(git describe --tags `git rev-list --tags --max-count=1`)
          VERSION_NUMBER=${LATEST_TAG#v}
          echo "Formatted version: $VERSION_NUMBER"
          cd client
          jq --arg v "$VERSION_NUMBER" '.version = $v' dist/manifest.json > temp.json && mv temp.json dist/manifest.json
      - run: |
          cd client
          bun deploy.js
      - name: Submit
        run: |
          cd client
          bunx chrome-webstore-upload-cli@2 upload --source extension.zip --auto-publish
        env:
          EXTENSION_ID: ${{ secrets.EXTENSION_ID }}
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}